server:
  port: 8081

spring:
  profiles:
    active: local
    group:
      local: common, domain, infrastructure
      prod: common, domain, infrastructure

internal:
  app:
    base-url: ${BASE_URL:http://localhost:8080}
    token: ${TOKEN:CHANGE}
    token-header-name: ${TOKEN_HEADER:X-Internal-Token}

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /admin/swagger-ui.html