server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      local: common, domain, infrastructure
      prod: common, domain, infrastructure

internal:
  admin:
    token: ${TOKEN:CHANGE}
    token-header-name: ${TOKEN_HEADER:X-Internal-Token}